name: JumpStart Compiler
run-name: Compile for All Platforms
on: [push]
jobs:
  Compile:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        branch: [win, mac]
        tag: [w, m]
        distfile: [JumpStart Setup , JumpStart-]
        filetype: [exe, pkg]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Get Package Version
        uses: polyseam/get-version-from-package-json@1.0.0
        id: package
        with:
          path-to-package-json: './package.json'
      - name: Install Packages
        run: npm install
      - name: Compile Binary
        run: npx electron-builder build -${{ matrix.tag }} -p never
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/${{ matrix.distfile }}${{ steps.package.outputs.version }}.${{ matrix.filetype }}
          asset_name: JumpStart_Setup-${{ matrix.branch }}.${{ matrix.filetype }}
          tag: v${{ steps.package.outputs.version }} ${{ matrix.branch }}
          prerelease: true
          overwrite: true
